# Read the documentation before extending the defaults:
# https://docs.searxng.org/admin/settings/

use_default_settings: true

server:
  secret_key: "41931b0ec46ad84a23cb33d5cb917ea08d4c86d6cf78394556a3c897a34b110e"
  image_proxy: true
  limiter: false

search:
  safe_search: 1
  autocomplete: "google"
  default_lang: ""
  formats:
    - html
    - json
  languages:
    - es-MX
    - en-US

outgoing:
  request_timeout: 10
  max_request_timeout: 25
  extra_proxy_timeout: 25

# Enabled engines
engines:
  # Web search engines
  - name: google
    engine: google
    shortcut: go
    use_mobile_ui: false

  - name: bing
    engine: bing
    shortcut: bi

  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg

  - name: startpage
    engine: startpage
    shortcut: sp
    timeout: 6.0

  - name: qwant
    engine: qwant
    shortcut: qw
    categories: general
    disabled: false

  # Tech engines
  - name: github
    engine: github
    shortcut: gh

  - name: stackoverflow
    engine: stackoverflow
    shortcut: so
    timeout: 10


